### ISSUE TITLE
My results...

### ISSUE THREAD

**Issue by aphillipo** [josevalim/gen_stage_bench#1]
Erlang/OTP 19 [erts-8.0.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

$ time mix run bench/multi_lazy.exs 
mix run bench/multi_lazy.exs  119.38s user 10.25s system 104% cpu 2:03.61 total

$ time mix run bench/multi_map_ets.exs 
#PID<0.139.0>
#PID<0.141.0>
#PID<0.138.0>
#PID<0.142.0>
#PID<0.140.0>
mix run bench/multi_map_ets.exs  48.37s user 5.72s system 134% cpu 40.238 total

$ time mix run bench/multi_map_reduce.exs 
#PID<0.142.0>
#PID<0.141.0>
#PID<0.143.0>
#PID<0.144.0>
#PID<0.145.0>
mix run bench/multi_map_reduce.exs  214.29s user 170.49s system 310% cpu 2:04.01 total

No idea what the results should be expected or why some are using so little CPU.

I have a need for GenStage for a thing I'm working on for work (that I probably cannot discuss in public) but it seems perfect for.  The documentation is really outstanding so now it's there I'll take a stab at using it :-)  Thanks!

**Comment by josevalim** [comment]
Thank you @aphillipo! We are trying different topologies and see which ones performs best for this simple problem. I have just pushed a new topology that should be roughly close to the map_ets one.

**Comment by aphillipo** [comment]
Yes I just saw this!

time mix run bench/multi_reduce.exs      
** (ArgumentError) argument error
    :erlang.hd([])
    bench/multi_reduce.exs:72: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:71: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3

**Comment by josevalim** [comment]
@aphillipo pass the demand as argument. like 100, 200, or 1000. I am usually running those with different demand values and see how it affects performance (:max_demand config).

**Comment by aphillipo** [comment]
You've made some changes - do you want me to rerun the whole lot?  Is this helpful?

**Comment by aphillipo** [comment]
$ time mix run bench/multi_reduce.exs 
{#PID<0.138.0>,
 [#PID<0.138.0>, #PID<0.139.0>, #PID<0.140.0>, #PID<0.141.0>, #PID<0.142.0>]}
{#PID<0.139.0>, [#PID<0.139.0>, #PID<0.140.0>, #PID<0.141.0>, #PID<0.142.0>]}
{#PID<0.142.0>, [#PID<0.140.0>, #PID<0.141.0>, #PID<0.142.0>]}
{#PID<0.140.0>, [#PID<0.140.0>, #PID<0.141.0>]}
{#PID<0.141.0>, [#PID<0.141.0>]}
mix run bench/multi_reduce.exs  117.53s user 8.13s system 622% cpu 20.190 total

**Comment by josevalim** [comment]
@aphillipo nah, it is alright. :) this is just fun for now! thanks for running it too and let me know if you have any questions!

**Comment by aphillipo** [comment]
At least you know it works elsewhere!  I will let you know once I have a repo working for the network scanner 😆
